s-panferov/awesome-typescript-loader

- src/index.ts
In TS1.5.3 `readConfigFile ` [signature](https://github.com/TypeStrong/ntypescript/blob/master/bin/typescriptServices.d.ts#L5288) has changed.
> tsconfig read fix

- src/helpers.ts
- src/host.ts
if outDir option in tsconfig.json is set, input and output files have different paths and loader produces error 'no output found' since it can not match produced files with source files. 
This PR fixes that.
> Added support for different TS compile destination 

- src/host.ts
- src/index.ts
There were a couple of problems here, fixed over two commits. Firstly, if a moduleResolution option was given in the tsconfig.json file, awesome-typescript would fail to compile any files. This was a problem if you needed "classic" resolution.
The other problem occurred with relative paths. Under windows, some paths weren't being normalized by awesome-typescript-loader, resulting in `C:\site\file.ts` instead of `C:/site/file.ts`. When compared, these were found to be not equal. This was fixed by normalizing all paths before they were saved in the State class.
> Fixes issues under windows with typescript 1.6, and moduleResolution flags

- src/host.ts
This fixes the hot reloading for typescript. The problem occurred because webpack expected windows path with backslashes, but the typescript normalizePath function used forward slashes.
I've tested this with both building and using the webpack-dev-server for both html/css/ts files and they all work correctly.
Fixes #72
> Fixed live reloading in windows, fixes #72

- .npmignore
- README.md
- package.json
- src/helpers.ts
- src/host.ts
- src/instance.ts
- src/test/index.ts
- src/tsconfig.json
> ignoreDiagnostics like ts-loader

- README.md
> Add babelCore docs to readme

- src/host.ts
Awesome-typescript-loader throws the following error when types are used in tsconfig.json
```
ERROR in ./src/main/frontend/main.ts
Module build failed: ReferenceError: ts is not defined
at C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\awesome-typescript-loader\src\host.ts:143:23
at Array.forEach (native)
at State.loadTypesFromConfig (C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\awesome-typescript-loader\src\host.ts:142:27)
at new State (C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\awesome-typescript-loader\src\host.ts:136:14)
at Object.ensureInstance (C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\awesome-typescript-loader\src\instance.ts:151:19)
at compiler …
```
> fix: ReferenceError: ts is not defined

- src/instance.ts
to improve watch stability when using OldWatchPlugin or WatchIgnorePlugin.
See https://github.com/TypeStrong/ts-loader/issues/155
> Apply https://github.com/TypeStrong/ts-loader/pull/167 

- src/deps.ts
- src/helpers.ts
- src/host.ts
As of https://github.com/Microsoft/TypeScript/pull/9646, TypeScript no longer expects extensions
in dependency resolution functions.
This should fix https://github.com/s-panferov/awesome-typescript-loader/issues/221.
> Remove file extensions while resolving dependencies.

- src/instance.ts
TypeScript 2.2's compilerConfig does not seem to include a typingOptions key.
I'm not sure if this can typecheck, but it does fix a runtime crash.
> Fix `TypeError: Cannot set property 'exclude' of undefined`

- README.md
the readme incorrectly referenced CheckerRuntime - when copied into
webpack.config.js, an error is thrown stating that CheckerRuntime
is not a constructor. The correct variable to use is CheckerPlugin.
Closes: #298
> docs(README): fix incorrect reference to CheckerPlugin

- src/instance.ts
in the latest webpack beta, the watcher property is moved one level
deeper, from watchFileSystem.watcher to watchFileSystem.wfs.watcher.
this change prevents a null pointer exception in regards to referencing
mtimes.
Closes: #300
> fix: reference wfs.watcher if watchFileSystem.watcher not exists

- .gitignore
- package.json
- prod/tsconfig.json
- src/defines.d.ts
- src/index.ts
- src/test/utils.ts
- tsconfig.json
Based on my research on issue #326 It seems like we should be using file references going forward.
These commits make a few minor fixes/tweaks and switch to using file references from the tsconfig.json as this is the current preferred way to add file references to a project.
I believe this should fix most of the issues that are breaking the build. In general, we should switch back to module references I believe, but better to fix build and then make a decision about that
> fix: Create file references for typescriptServices

- src/checker/send.ts
fix the RPC sending to loop with a delay between each send to alleviate pressure on the RPC pipe.
The key here is to setImmediate between processing messages, note that this is a similar work-around to how vscode ts support works - only their queue is promise based, so the delay is implicit.
> Fixes a case where windows + awesome-typescript-loader can still hang waiting for IPC with the checker

- src/index.ts
Had an error where result.deps was undefined. Can't honestly explain the root cause, but this addition fixes the error for me.
> fix: undefined error on result.deps

- package.json
- src/index.ts
loader-utils 0.2.17 shows a [deprecation warning](https://github.com/webpack/loader-utils/pull/57/files) for parseQuery. It shows when you pass the options as object to awesome-typescript-loader like:
```javascript
rules: [
{
test: /\.ts$/,
use: {
loader: `awesome-typescript-loader`,
query: {
configFileName: `${param.sourceRoot}/js/tsconfig.json`,
}
},
},
``` 
you see:
This PR updates to 1.0.2 and uses the new `getOptions` method.
> update loader-utils to ^1.0.2

- src/instance.ts
`watchpack 1.3.0` no longer returns `mtimes` and build fails
Fixes https://github.com/s-panferov/awesome-typescript-loader/issues/378
> Fix: add check for missing "mtimes"

- src/__test__/error.ts
- src/checker/runtime.ts
When outputting the diagnostics from a compiled file, the filename would be outputted relative to the context the loader was run, but without a leading './'. This PR adds this leading './'
> feat: Ensure errors are outputted as relative paths (i.e. begin with './')

- src/instance.ts
This allows to run the webpack and sucessfully compiles it from a parent folder, has long as the webpack context is well set.
The path plugin could also benefit from using the webpack context, but the context is passable as an option, so I guess it's fine.
> Change the context to webpack provided one

- src/__test__/react.ts
- src/instance.ts
Previously, the `setupCache` function always returned `undefined`, so it seems that cache invalidation based on the environment has never worked.
This fixes that bug, and also add and removes some parameters for the cacheIdentifier.
Removes:
- `awesome-typescript-loader-query` - because this is already included in the cache key elsewhere (https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/cache.ts#L70)
Adds:
- `compilerConfig` - the typescript compiler configuration
- `babelPkg` - babel config in package.json
- `env` - process environment variables that babel can potentially use
We should also look up the directory tree for `babelrc.js`/`babelrc.json` files, but I think this is at least good start for now.
> fix: environment cache invalidation

- src/instance.ts
- Removed check for compilation.bail = true and treat error message as in non-bail mode.
- Loader is not killed anymore (removed process.exit(1)) as this should be done by the caller of the loader.
- All error messages are reported now as they are already generated at that moment (no need to suppress them).
> Don't kill the loader when compilation.bail = true

- package.json
- tsconfig.json
- yarn.lock
enhanced-resolve upgraded to v3.3.0 due to a compilation error with
@angular/cli [#7113](https://github.com/angular/angular-cli/issues/7113)
tsconfig.json upgraded due to missing node and mocha type definitions
> fix(dependencies): upgrading node dependencies

- src/checker/checker.ts
This allows passing command-line options other than `--debug` and `--inspect` through to the type checker child process, e.g. `--max-old-space-size` to increase the available memory.
We are currently experiencing out-of-memory errors with TypeScript 2.4 and some complex types that we depend on. While we are working on fixing the typings to reduce memory consumption, we wanted to use the `--max-old-space-size` option as a workaround to increase the available memory for the Node.js process. We noticed however that this option is not being passed through to the type checker child process which is created by awesome-typescript-loader, only `--debug` or `--inspect` are passed.
This PR keeps the special treatment for `--debug` and `--inspect`, but passes all other options through to the created …
> fix(checker): pass through execArgv to checker child process

- package.json
- src/instance.ts
- yarn.lock
* depends on the latest `source-map-support`
* no need to depend on `object-assign`, use the object-spread operator instead
* add `typescript` to peedDependencies
> cleanup dependencies

- README.md
when enabling `transpileOnly`, even there is `CheckerPlugin` configrated in webpack.config.js, it will not take effect.
ideally we should print some warning in this situation but I think a precise notice in the docs should be sufficient at this moment.
> Specify `transpileOnly` option

- src/index.ts
The emitter expects to receive an error object instead of a plain string:
```
[0] WARNING in ../my-app/my-file.d.ts
[0] (Emitted value instead of an instance of Error) [at-loader] TypeScript declaration files should never be required
```
> Use Error for emitted warn

- src/checker/runtime.ts
- src/interfaces.ts
This is something that we've been using for the past half a year and I thought it'd be good to get it in upstream. Fixes #447.
I guess this does the same thing as this other PR (closes #423) except we're not introducing a new config. If the `getCustomTransformers` is a string, it's assumed to be a module that can be simply required so either something that can be found in the parent `node_modules` or an absolute module path. If it's a function, then the code works as before.
Another difference is that the function is not given the Program object. I don't know how useful this is or not, but it can be easily added.
Let me know if you need me to do anything else for this. Probably a test or two would be in order.
> Fix custom transformers when using fork checker

- src/cache.ts
- src/checker/checker.ts
- src/checker/index.ts
- src/checker/protocol.ts
- src/checker/runtime.ts
- src/checker/send.ts
- src/entry.ts
- src/helpers.ts
- src/index.ts
- src/instance.ts
- src/interfaces.ts
- src/paths-plugin.ts
- src/watch-mode.ts
This works with the changes of Microsoft/TypeScript#20234
> Using the new watch api of compiler 

- src/instance.ts
- src/watch-mode.ts
- Move to the new Tapable API.
- Remove`instance.checker.getFiles()` from being placed into `instance.compiledFiles`. This prevents files loaded automatically by the typescript compiler, such as `typescript/lib/lib.dom.d.ts`, from being incorrectly set as removed when the Webpack watcher runs. This is because such files are not known to the Webpack watcher and are missing from `watcher.getTimes()`.
> Fixes for Webpack 4, contributes towards #534

- src/checker/runtime.ts
In your implementation getDefaultLibLocation function is not implemented. Therefore `ts.getDirectoryPath(getDefaultLibraryFileName())` will be called which returns drive letter if called with Windows slashes which is wrong.
Though might be implementing getDefaultLibLocation will be a bit better solution but keep in mind:
1. Some functions are not accessible in .d.ts
2. This still causes issues and needs to be fixed.
So I think this solution is perfectly fine. closes #548. Worth mentioning #534
> fix default library path discovery on Windows OS

- package.json
- src/checker/runtime.ts
- src/instance.ts
- yarn.lock
Closes #567.
I just opened #567 and actually decided to give it a shot myself. I find the result pretty enjoyable actually, well integrated with other Webpack tooling when building.
Note that I have only changed what I was able to output, so there are a bunch of other `console.{log,error}` that I left untouched. I think they can be switched iteratively, but also happy to take care of them if you want me to, in which case I would appreciate further instructions how to trigger them :)
Some results:
Before | After
--- | ---
With `debug` on:
> Use webpack-log for nicer logging

- src/instance.ts
Fixes #443, and possibly #232, #252, #346 as well.
TypeScript [expects the system host to provide Unix-style paths](https://github.com/Microsoft/TypeScript/blob/v2.1.1/src/compiler/core.ts#L1233). Passing a Windows-style configFilePath causes config-relative paths (such as typeRoots) to be incorrectly resolved.
> fix: pass Unix-style path to config parser

- src/instance.ts
It looks like awesome-typescript-loader@5 works with at least webpack version 4 but this is not checked in its code. So the errors that users get look like this:
```
TypeError: Cannot read property 'watchRun' of undefined
at setupWatchRun (/Users/dsorin/ecosystem/dac/packages/app-management-apollo/node_modules/awesome-typescript-loader/src/instance.ts:372:16)
at Object.ensureInstance (/Users/dsorin/ecosystem/dac/packages/app-management-apollo/node_modules/awesome-typescript-loader/src/instance.ts:141:2)
at compiler (/Users/dsorin/ecosystem/dac/packages/app-management-apollo/node_modules/awesome-typescript-loader/src/index.ts:47:19)
at Object.loader (/Users/dsorin/ecosystem/dac/packages/app-management-apollo/node_modules/awesome-typescript-loader/src/index.ts:16:12)
at LOADER_EXECUTION …
```
> Assertion check for webpack version

- src/index.ts
- src/instance.ts
Hello,
I changed the way declaration files are written on disk, this way they appear in webpack's output report.
The file paths stay the same and the features are identical.
> Use webpack to write declaration files, gives better reporting
